### ISSUE TITLE
Compile/Add ncurses v5.9 (linux only)

### ISSUE THREAD

**Issue by Dankr4d** [Dankr4d/BF2142Unlocker#3]
To run the Battlefield 2142 server in linux, ncurses v5.9 is required. Currently I'm compiling the old version in centos, because ncurses must be compiled with an older gcc.
Try to build ncurses on linux when running the build script.
Copy the ncurses library into server bin/amd-64 path.

**Comment by Dreaded-Gnu** [comment]
Have you tried to create a patch for ncurses 5.9, so that it can be compiled using an updated gcc?

Found a patch where someone prepared ncurses 5.9 for a more recent gcc, because they stuck also at that point ([patch](https://raw.githubusercontent.com/cloudius-systems/osv/07e2d9032dbb3f4f2b0d0133e0eccd5be05dd05d/modules/ncurses/ncurses-5.9-gcc-5.patch))

A patch like this might be applied by using command like `patch -d /path/to/dir -p0 < /path/to/patch`. Patch command might not work out of the box.

**Comment by Dankr4d** [comment]
Compilation of ncurses 5.9 works when applying the patch and passing `--without-cxx-binding` parameter to configure.
Used configure command:
`./configure --with-shared --without-debug --without-normal --without-cxx-binding`
