### ISSUE TITLE
How to join a LAN server? 

### ISSUE THREAD

**Issue by j2ybb** [Dankr4d/BF2142Unlocker#60]
I set up a LAN server on my own computer(not dedicated server) Then use another computer in the same LAN to try to join The server is normal, but the client is always in the black screen after inputting IP and clicking connect.  

My Run Server steps : 1. PC-1: Run BF2142Unlocker.exe  click "Host" Then wait for the client in the main menu.   2. PC-2: Run BF2142Unlocker.exe  Enter the IP address of the server   click "Connect"  Then the game works normally, but the screen is always black. Wait about a few minutes before the game doesn't respond. 
I noticed that the server terminal didn't have any information about the client connection
 Sorry for my poor English
My 2142 pack :- BF2142 v1.51 by Novgames    OS: Win10 x64

**Comment by Dankr4d** [comment]
Well, this means that the client cannot reach one or all 3 servers the unlocker is hosting on the other PC (I disabled the checks if the servers are reachable in this version, since it wasn't asynchronous and not worked well on linux). One problem could be that windows firewall is blocking incoming data on those ports. You could check this and open those ports that are shown in the terminal output and check if it's working then.

Workaround:
A workaround you could try (if you play in LAN), is to click on`Singleplayer` on both PC's. The game should start as usual and you should see the the LAN game in the menu after one of your PC's hosted one. The only difference you have then, is that both clients are hosting and communicating with their own login and unlock servers. If you still do not see the game server (which shouldn't happen) you can connect in game via `Multiplayer` -> `Advanced` -> `Connect to IP`.

**Comment by j2ybb** [comment]
I have successfully tested the connection in version 0.9.5
First, the server needs to click "Host" button, and then wait for the client in the game lobby. then the client needs to click the "Singleplayer" button, After entering the main menu of the game, you can exit the game. Please don't click at this time BF2142Unlocker.exe "Cancel" button. At this time, you can enter the IP address of the server(192.168.x.x). Click the "Connect" button and you will be able to enter the game successfully. This method of connecting to the lan server is a bit complicated. Can you optimize for this ?

**Comment by j2ybb** [comment]
> Well, this means that the client cannot reach one or all 3 servers the unlocker is hosting on the other PC (I disabled the checks if the servers are reachable in this version, since it wasn't asynchronous and not worked well on linux). One problem could be that windows firewall is blocking incoming data on those ports. You could check this and open those ports that are shown in the terminal output and check if it's working then.
> 
> Workaround:
> A workaround you could try (if you play in LAN), is to click on`Singleplayer` on both PC's. The game should start as usual and you should see the the LAN game in the menu after one of your PC's hosted one. The only difference you have then, is that both clients are hosting and communicating with their own login and unlock servers. If you still do not see the game server (which shouldn't happen) you can connect in game via `Multiplayer` -> `Advanced` -> `Connect to IP`.

I have successfully tested the connection in version 0.9.5
First, the server needs to click "Host" button, and then wait for the client in the game lobby. then the client needs to click the "Singleplayer" button, After entering the main menu of the game, you can exit the game. Please don't click at this time BF2142Unlocker.exe "Cancel" button. At this time, you can enter the IP address of the server(192.168.x.x). Click the "Connect" button and you will be able to enter the game successfully. This method of connecting to the lan server is a bit complicated. Can you optimize for this ?

**Comment by Dankr4d** [comment]
Well this is weird. The workaround you described shouldn't either work (did a short code review), except the client that is trying to connect is now able to reach the other login/unlock servers.

Let me explain how those two "Host" and "Singleplayer" buttons work. Both buttons are hosting the login and unlock server. The addresses the servers (login and unlock) is listening to are patched into the BF2142Patched.exe (working copy of BF2142.exe).
When you click "Host" the servers are listening on 0.0.0.0 and the game is patched 127.0.0.1.
When you click "Singleplayer" the servers are listening on 127.0.0.1 and the game is patched to 127.0.0.1.
Means, when clicking "Host" everyone can connect to your login and unlock servers and your game is patched to connect to your local ip address.  When clicking "Singleplayer" only you are able to connect to your login and unlock server.
Since the game server doesn't care about on which login/unlock server you're connected to, there is no difference when both are clicking on "Singleplayer".
The "Connect" button just patches the ip addresses the game should connect to (login and unlock server). With version 0.9.5 it doesn't check if those servers are reachable and just starts the game. If the game cannot connect, the game will stuck in a black screen because the timeout of the game is set to high (the timeout is not set by unlocker). It will take minutes until the game connection attempt to the login and unlock server timeouts.
So the workaround you described is more complicated than the workaround I wrote above. Please try to click on Singleplayer on both PC's.

> Can you optimize for this ?

Since this is not the way how it is supposed to work there's nothing to optimize. If there's a bug then I need to fix it. The way you tried to connect first is the way it is supposed to work.


Back to your workaround, to get this fixed for you and others. A few questions..
* Have you tried to cancel your local login/unlock servers (clicking on the cancel button)? Does it still work when you click on cancel?
* If it's not working when clicking on cancel, do you need to do this procedure always or only once and it's working now without problem anymore?
* Does it work when both are just clicking on "Singleplayer"?

**Comment by j2ybb** [comment]
> 好吧，这很奇怪。您描述的变通办法都不起作用（简短的代码回顾），除了尝试连接的客户端现在可以访问其他登录/解锁服务器。
> 
> 让我解释一下这两个“主机”和“单人”按钮的工作方式。这两个按钮都托管着登录和解锁服务器。服务器（登录和解锁）正在侦听的地址被修补到BF2142Patched.exe（BF2142.exe的工作副本）中。
> 当您单击“主机”时，服务器正在监听0.0.0.0，并且游戏已打补丁127.0.0.1。
> 当您单击“单人”时，服务器正在侦听127.0.0.1，并且游戏已修补到127.0.0.1。
> 意味着，单击“主机”时，每个人都可以连接到您的登录名并解锁服务器，并且您的游戏已打补丁以连接到您的本地IP地址。单击“ Singleplayer”时，您只能连接到登录和解锁服务器。
> 由于游戏服务器不关心您连接的登录/解锁服务器，因此两者都单击“单人游戏”时没有区别。
> “连接”按钮只是修补游戏应连接到的IP地址（登录并解锁服务器）。在0.9.5版中，它不会检查这些服务器是否可用，而只是开始游戏。如果游戏无法连接，则游戏将停留在黑屏中，因为游戏的超时设置为高（解锁器未设置超时）。游戏连接尝试登录并解锁服务器超时之前需要几分钟。
> 因此，您描述的解决方法比我上面编写的解决方法更为复杂。请尝试在两台PC上单击“单人游戏”。
> 
> > 您可以为此优化吗？
> 
> 由于这不是应该如何工作的方式，因此没有任何要优化的地方。如果有错误，那么我需要修复它。您首先尝试进行连接的方式就是它应该工作的方式。
> 
> 回到您的解决方法，为您和其他人解决此问题。几个问题..
> 
> * 您是否尝试取消本地登录/解锁服务器（单击“取消”按钮）？当您单击取消时，它仍然有效吗？
> * 如果单击“取消”时它不起作用，您是否需要始终执行此过程或仅执行一次此过程，现在它就可以正常工作了？
> * 当两者都单击“ Singleplayer”时，它是否起作用？



> Well this is weird. The workaround you described shouldn't either work (did a short code review), except the client that is trying to connect is now able to reach the other login/unlock servers.
> 
> Let me explain how those two "Host" and "Singleplayer" buttons work. Both buttons are hosting the login and unlock server. The addresses the servers (login and unlock) is listening to are patched into the BF2142Patched.exe (working copy of BF2142.exe).
> When you click "Host" the servers are listening on 0.0.0.0 and the game is patched 127.0.0.1.
> When you click "Singleplayer" the servers are listening on 127.0.0.1 and the game is patched to 127.0.0.1.
> Means, when clicking "Host" everyone can connect to your login and unlock servers and your game is patched to connect to your local ip address. When clicking "Singleplayer" only you are able to connect to your login and unlock server.
> Since the game server doesn't care about on which login/unlock server you're connected to, there is no difference when both are clicking on "Singleplayer".
> The "Connect" button just patches the ip addresses the game should connect to (login and unlock server). With version 0.9.5 it doesn't check if those servers are reachable and just starts the game. If the game cannot connect, the game will stuck in a black screen because the timeout of the game is set to high (the timeout is not set by unlocker). It will take minutes until the game connection attempt to the login and unlock server timeouts.
> So the workaround you described is more complicated than the workaround I wrote above. Please try to click on Singleplayer on both PC's.
> 
> > Can you optimize for this ?
> 
> Since this is not the way how it is supposed to work there's nothing to optimize. If there's a bug then I need to fix it. The way you tried to connect first is the way it is supposed to work.
> 
> Back to your workaround, to get this fixed for you and others. A few questions..
> 
> * Have you tried to cancel your local login/unlock servers (clicking on the cancel button)? Does it still work when you click on cancel?
> * If it's not working when clicking on cancel, do you need to do this procedure always or only once and it's working now without problem anymore?
> * Does it work when both are just clicking on "Singleplayer"?

1. Click Cancel and the game will prompt you to disconnect from EA master server

2. Both sides click the  "Singleplayer" , and when they join the server in the LAN of the game, they will be prompted to disconnect from the server, which is the problem that the LAN of the original version 1.51 cannot join the server

The solution that I successfully tested seems to be that after the client clicks the  "Singleplayer", it makes an account login and then connects to the server of the host computer

**Comment by j2ybb** [comment]
> Well this is weird. The workaround you described shouldn't either work (did a short code review), except the client that is trying to connect is now able to reach the other login/unlock servers.
> 
> Let me explain how those two "Host" and "Singleplayer" buttons work. Both buttons are hosting the login and unlock server. The addresses the servers (login and unlock) is listening to are patched into the BF2142Patched.exe (working copy of BF2142.exe).
> When you click "Host" the servers are listening on 0.0.0.0 and the game is patched 127.0.0.1.
> When you click "Singleplayer" the servers are listening on 127.0.0.1 and the game is patched to 127.0.0.1.
> Means, when clicking "Host" everyone can connect to your login and unlock servers and your game is patched to connect to your local ip address. When clicking "Singleplayer" only you are able to connect to your login and unlock server.
> Since the game server doesn't care about on which login/unlock server you're connected to, there is no difference when both are clicking on "Singleplayer".
> The "Connect" button just patches the ip addresses the game should connect to (login and unlock server). With version 0.9.5 it doesn't check if those servers are reachable and just starts the game. If the game cannot connect, the game will stuck in a black screen because the timeout of the game is set to high (the timeout is not set by unlocker). It will take minutes until the game connection attempt to the login and unlock server timeouts.
> So the workaround you described is more complicated than the workaround I wrote above. Please try to click on Singleplayer on both PC's.
> 
> > Can you optimize for this ?
> 
> Since this is not the way how it is supposed to work there's nothing to optimize. If there's a bug then I need to fix it. The way you tried to connect first is the way it is supposed to work.
> 
> Back to your workaround, to get this fixed for you and others. A few questions..
> 
> * Have you tried to cancel your local login/unlock servers (clicking on the cancel button)? Does it still work when you click on cancel?
> * If it's not working when clicking on cancel, do you need to do this procedure always or only once and it's working now without problem anymore?
> * Does it work when both are just clicking on "Singleplayer"?

BF2142Unlocker.exe Terminal
Unlock (HTTP) server listening on 127.0.0.1:8085 and waiting for clients!
Login (UDP) server listening on 127.0.0.1:29900 and waiting for clients!
Login (TCP) server listening on 127.0.0.1:18300 and waiting for clients!

My port log
TCP    127.0.0.1:8085         0.0.0.0:0                   LISTENING       9556
TCP    127.0.0.1:8085         127.0.0.1:58150        TIME_WAIT       0
TCP    127.0.0.1:8085         127.0.0.1:58154        TIME_WAIT       0
TCP    127.0.0.1:8085         127.0.0.1:58155        TIME_WAIT       0
TCP    127.0.0.1:8085         127.0.0.1:58156        TIME_WAIT       0
TCP    127.0.0.1:8085         127.0.0.1:58157        TIME_WAIT       0
TCP    127.0.0.1:10000        0.0.0.0:0                  LISTENING       100
TCP    127.0.0.1:18300        0.0.0.0:0                  LISTENING       9556
TCP    127.0.0.1:18300        127.0.0.1:58151     ESTABLISHED     9556
TCP    127.0.0.1:29900        0.0.0.0:0                  LISTENING       9556
TCP    127.0.0.1:29900        127.0.0.1:58153     ESTABLISHED     9556

Is this normal work?

**Comment by Dankr4d** [comment]
Well, it looks ok to me.
I'll investigate the issue you described and I will test it step by step to get why it isn't working for you and if I get the same issues.
With version 0.9.5 I reworked the gui and how to use it, maybe this could be the problem. I'll keep you up to date.
